"""Turning a task's note reference into a link, but only when there is one.

A task made by circling handwriting on the Supernote carries the notebook and
page it came from, and the connector writes that onto the task as a line of
prose. This resolves that line against the notebooks Task Hub has actually
backed up, so the task can offer the same jump the tablet does -- straight to
the page, in a PDF that is already on disk.

The rule that matters is the one asked for: **no link unless the notebook is
here.** A reference to a notebook nobody chose to back up is still worth
showing as text, because it says where the task came from, but it must not
look clickable. A link that goes nowhere is worse than no link: it invites a
tap, spends a moment loading, and answers with an error for something that was
never wrong.

Resolved at render time rather than stored. The answer changes when somebody
ticks a folder, unticks one, or removes a copy, and a stored link would be
wrong from that moment until the next sync noticed.
"""

from __future__ import annotations

import re

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db.models import ServiceKind, SupernoteNote
from app.sync import note_backup

#: The line the connector writes. Matched rather than parsed loosely, because
#: it is generated by one place in this codebase and a fuzzy match would start
#: finding references in notes somebody typed themselves.
_REFERENCE = re.compile(
    r"From (?P<name>[^\n,]+?\.note)(?:, page (?P<page>\d+))?\s*$",
    re.MULTILINE,
)


def reference_in(text: str | None) -> tuple[str, int | None] | None:
    """The notebook and page a task refers to, if it names one."""
    if not text:
        return None
    match = _REFERENCE.search(text)
    if match is None:
        return None
    page = match.group("page")
    return match.group("name"), int(page) if page else None


def link_for(db: Session, item) -> dict | None:
    """Where to send somebody who taps the notebook beside a task.

    Returns None whenever there is nothing to open -- a task from another
    service, a reference to a notebook that is not backed up, a backup whose
    file has since gone. Each of those is a case where the reference should
    still read as text and not as a link.
    """
    if getattr(item, "origin_service", None) != ServiceKind.SUPERNOTE:
        return None

    found = reference_in(getattr(item, "notes", None))
    if found is None:
        return None
    name, page = found

    # Supernote stores the notebook as "<name>.note"; Task Hub records it
    # without the suffix, which is how it is displayed everywhere else.
    stem = name[:-5] if name.lower().endswith(".note") else name
    row = db.execute(
        select(SupernoteNote).where(SupernoteNote.name == stem)
    ).scalars().first()

    if row is None or not row.pdf_name or row.excluded:
        return None
    # The row can outlive the file -- a restore from an older backup, a disk
    # tidied by hand. Checked rather than assumed, because this is precisely
    # the link that must not be offered when it cannot work.
    if not note_backup.pdf_path(row).exists():
        return None

    # The fragment is understood by every browser PDF viewer and ignored
    # harmlessly by the ones that are not.
    target = f"/notes/{row.id}/pdf"
    if page:
        target += f"#page={page}"
    return {
        "url": target,
        "name": stem,
        "page": page,
        "title": f"Open {stem}" + (f" at page {page}" if page else ""),
    }


# --- Obsidian ------------------------------------------------------------------

#: The URI the Obsidian connector writes under a task, which opens the vault and
#: the note the task was read from.
_OBSIDIAN = re.compile(r"obsidian://open\?[^\s<>\"']+")

#: The human-readable line above it: the vault and the path within it.
_OBSIDIAN_WHERE = re.compile(r"^—\s*Obsidian\s*·\s*(?P<path>.+?)\s*$", re.MULTILINE)


def obsidian_link(item) -> dict | None:
    """Where to send somebody who wants the note a task came from.

    The connector already writes both a readable path and an ``obsidian://``
    URI into the task's notes, because those have to survive into services that
    know nothing about Task Hub. Here there is a real interface, so the URI
    becomes a button and stops being a line of raw text nobody can use.

    Returns None when the task did not come from a vault or carries no URI --
    an older task, or one somebody rewrote by hand.
    """
    text = getattr(item, "notes", None)
    if not text or "obsidian://" not in text:
        return None
    match = _OBSIDIAN.search(text)
    if match is None:
        return None
    where = _OBSIDIAN_WHERE.search(text)
    path = where.group("path") if where else ""
    return {
        "url": match.group(0),
        "name": path.rsplit("/", 1)[-1] or "the note",
        "path": path,
        "title": f"Open {path or 'this note'} in Obsidian",
    }


def without_obsidian_link(text: str | None) -> str | None:
    """The notes with the machine-readable parts taken out, for display.

    The URI is shown as a button beside the task, so leaving it in the text as
    well means a wall of percent-encoding under every task read from a vault.
    The readable path goes too, since the button names it.
    """
    if not text:
        return text
    cleaned = _OBSIDIAN.sub("", text)
    cleaned = _OBSIDIAN_WHERE.sub("", cleaned)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned).strip()
    return cleaned or None
